// lib/menu.js
export const MENU_ITEMS = [
  {
    id: 'afghani-chaap',
    name: 'Afghani Chaap',
    description: 'Marinated in rich Afghani spices, grilled to perfection with aromatic herbs',
    image: '/afghani_chaap.png',
    emoji: '🔥',
    half: 80,
    full: 150,
    tag: 'Chef\'s Pick',
    tagColor: '#FF6B00',
  },
  {
    id: 'malai-chaap',
    name: 'Malai Chaap',
    description: 'Creamy malai coating with saffron & cardamom, melt-in-mouth texture',
    image: '/malai_chaap.png',
    emoji: '✨',
    half: 80,
    full: 150,
    tag: 'Fan Favourite',
    tagColor: '#9333ea',
  },
  {
    id: 'tandoori-chaap',
    name: 'Tandoori Chaap',
    description: 'Classic tandoori marination with charcoal smoke flavour, served with mint chutney',
    image: '/tandoori_chaap.png',
    emoji: '🌶️',
    half: 90,
    full: 160,
    tag: 'Spicy',
    tagColor: '#ef4444',
  },
  {
    id: 'seekh-chaap',
    name: 'Seekh Chaap',
    description: 'Minced chaap with green chilli & coriander, shaped into juicy seekh kebabs',
    image: '/seekh_chaap.png',
    emoji: '🍢',
    half: 90,
    full: 160,
    tag: 'Street Special',
    tagColor: '#0ea5e9',
  },
  {
    id: 'paneer-tikka',
    name: 'Paneer Tikka',
    description: 'Premium paneer marinated in tikka masala, grilled with capsicum & onion',
    image: '/paneer_tikka.png',
    emoji: '🧀',
    half: 100,
    full: 180,
    tag: 'Veg Delight',
    tagColor: '#22c55e',
  },
]

export const TABLES = [
  { id: 'T1', label: 'Table 1' },
  { id: 'T2', label: 'Table 2' },
  { id: 'T3', label: 'Table 3' },
  { id: 'T4', label: 'Table 4' },
  { id: 'OUT', label: 'Outside (Standing)' },
]
